remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Awalin's Portfolio
description: I am a compassionate technologist who makes sense of data for people.
show_downloads: false

